CREATE TABLE IF NOT EXISTS "stucms_teacher" (
                                             "teacher_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "name" varchar NOT NULL,
                                             "phone" varchar,
                                             "sex" varchar,
                                             "qq" varchar,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             PRIMARY KEY ("teacher_id")
) COMMENT '老师表';

CREATE TABLE IF NOT EXISTS "stucms_course" (
                                            "course_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            "course_name" varchar NOT NULL,
                                            "course_full" int NOT NULL,
                                            "teacher_id" bigint NOT NULL,
                                            "creator" varchar DEFAULT '',
                                            "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "updater" varchar DEFAULT '',
                                            "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            "deleted" bit NOT NULL DEFAULT FALSE,
                                            PRIMARY KEY ("course_id")
) COMMENT '课程表';

CREATE TABLE IF NOT EXISTS "stucms_student" (
                                                "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                "student_uid" varchar NOT NULL,
                                                "student_name" varchar NOT NULL,
                                                "sex" varchar NOT NULL,
                                                "phone" varchar NOT NULL,
                                                "sysid" varchar NOT NULL,
                                                "birth" datetime NOT NULL,
                                                "minzu" varchar NOT NULL,
                                                "hukou" varchar,
                                                "jishu" varchar NOT NULL,
                                                "huji" varchar,
                                                "xianzz" varchar,
                                                "liushou" bit NOT NULL,
                                                "biye" varchar,
                                                "huojiang" varchar,
                                                "creator" varchar DEFAULT '',
                                                "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                "updater" varchar DEFAULT '',
                                                "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                "deleted" bit NOT NULL DEFAULT FALSE,
                                                PRIMARY KEY ("student_id")
) COMMENT '学生表';

